{application,erlymud,
             [{description,"ErlyMUD Game Server"},
              {vsn,"0.1.1"},
              {registered,[erlymud_sup]},
              {applications,[kernel,stdlib,tcp_interface]},
              {mod,{erlymud_app,[]}},
              {env,[]},
              {modules,[em_grammar,em_object,em_user,erlymud,erlymud_app,
                        erlymud_cmd,erlymud_room,erlymud_room_mgr,erlymud_sup,
                        erlymud_text,erlymud_user_sup,erlymud_users]}]}.
